#  飞书
APP_ID: cli_a4a2a0846139900d
APP_SECRET: EVEMf4dGrmdnTZDFHYMpULgoAiJScGwb
APP_ENCRYPT_KEY: 9mAeBTLYaC9iNLVRIndGgg4LWRVOEtFv
APP_VERIFICATION_TOKEN: 6ujn4FBbN8e5SFtbcwOlzd20MKGwAA1x
# 请确保和飞书应用管理平台中的设置一致
BOT_NAME: yunliChatGpt
# openAI key 支持负载均衡 可以填写多个key 用逗号分隔
OPENAI_KEY: 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
# 服务器配置
HTTP_PORT: 9000
HTTPS_PORT: 9001
USE_HTTPS: false
CERT_FILE: cert.pem
KEY_FILE: key.pem
# openai 地址, 一般不需要修改, 除非你有自己的反向代理
API_URL: https://api.openai.com
# 代理设置, 例如 "http://127.0.0.1:7890", ""代表不使用代理
HTTP_PROXY: ""
